name: fl_amap_map
description: AMap location and AMap plugin for flutter, supports single positioning and continuous positioning
version: 0.0.1
repository: https://github.com/Wayaer/fl_amap/tree/main/fl_amap_amap

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.13.0'

dependencies:
  flutter:
    sdk: flutter
  fl_channel: ^0.0.2

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: fl.amap.map
        pluginClass: AMapMapPlugin
      ios:
        pluginClass: AMapMapPlugin
