name: example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  fl_amap:
    path: ../
  flutter:
    sdk: flutter
  flutter_waya: ^2.2.0
  permission_handler: ^10.0.0

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
