name: amap
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  fl_amap:
    path: ../
  flutter:
    sdk: flutter
  flutter_waya: ^1.13.1
  permission_handler: ^7.2.0

flutter:
  uses-material-design: true
