name: amap
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  fl_amap:
    path: ../
  flutter:
    sdk: flutter
  permission_handler: ^6.0.1

flutter:
  uses-material-design: true
