name: fl_amap
description: AMap location plugin for flutter, supports single positioning and continuous positioning
version: 2.1.0
repository: https://github.com/Wayaer/fl_amap.git

environment:
  sdk: '>=2.12.1 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: fl.amap
        pluginClass: AMapPlugin
      ios:
        pluginClass: AMapPlugin
