name: fl_amap
description: AMap location plugin for flutter
version: 0.0.1
repository: https://github.com/Wayaer/flutter_curiosity.git

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: flutter.amap
        pluginClass: AMapPlugin
      ios:
        pluginClass: AMapPlugin
