name: fl_amap
description: AMap plugin for flutter
version: 2.5.3
repository: https://github.com/Wayaer/fl_amap

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1
