name: example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  fl_amap:
    path: ../
  flutter:
    sdk: flutter
  flutter_waya: ^8.4.0
  fl_dio: ^0.1.0
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
