name: example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  fl_amap:
    path: ../
  flutter:
    sdk: flutter
  flutter_waya: ^8.0.3
  permission_handler: ^10.4.3

dev_dependencies:
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
